version: '3'

services:
  grafana:
    image: grafana/grafana-enterprise:10.1.2  # Match the customer's Grafana version
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - renderer
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_LOG_LEVEL: debug

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
      - prometheus_data:/prometheus

  mysql:
    image: mysql:5.7  # Using MySQL 5.7 as an example
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  renderer:
    image: grafana/grafana-image-renderer:latest
    environment:
      - HOST=0.0.0.0
    ports:
      - "8081:8081"

volumes:
  grafana_data:
  mysql_data:
  prometheus_data:

